#!/usr/bin/env python

import sys
import getopt
import os
import logging
# TODO remove me
sys.path.append("/root/core")
sys.path.append("/home/vagrant/core")

from arkos.daemon import Daemon
from kraken.application import run_daemon

class KrakenDaemon(Daemon):
    def run(self):
        run_daemon(self.environment, self.log_level, self.config_file,
            self.secrets_file, self.policy_file)


def usage():
    print("""
Usage: kraken [options]
Options:
    -c, --config <file>  - Use given config file instead of default
    -e, --env <env>      - Set run environment (dev, vagrant, etc)
    -v                   - Debug/verbose logging
    -d, --start          - Run in background (daemon mode)
    -r, --restart        - Restart daemon
    -s, --stop           - Stop daemon
    -h, --help           - This help
    """)


if __name__ == '__main__':
    reload(sys)
    sys.setdefaultencoding('utf-8')
    sys.dont_write_bytecode = True

    log_level = logging.INFO
    config_file = ''

    try:
        opts, args = getopt.getopt(sys.argv[1:], 'hce:drsv', ['help', 'config=', 'env=', 'start', 'stop', 'restart'])
    except getopt.GetoptError as e:
        print((str(e)))
        usage()
        sys.exit(2)

    action = 'run'
    environment = 'prod'

    for o, a in opts:
        if o in ('-h', '--help'):
            usage()
            sys.exit(0)
        elif o in ('-v',):
            log_level = logging.DEBUG
        elif o in ('-c', '--config'):
            if os.path.isfile(a):
                config_file = a
        elif o in ('-e', '--env'):
            environment = a
        elif o in ('-d', '--start'):
            action = 'start'
        elif o in ('-r', '--restart'):
            action = 'restart'
        elif o in ('-s', '--stop'):
            action = 'stop'

    # Find default config file
    if not config_file:
        if environment == "prod":
            config_file = "/etc/arkos/settings.json"
        else:
            config_file = os.path.join(os.path.dirname(__file__), 'settings.json')
    secrets_file = os.path.join(os.path.dirname(config_file), "secrets.json")
    policy_file = os.path.join(os.path.dirname(config_file), "policies.json")

    if action == 'run':
        run_daemon(environment, log_level, config_file, secrets_file, policy_file)
    else:
        krakend = KrakenDaemon('/var/run/kraken.pid', stdout='/var/log/kraken.log')
        krakend.environment = environment
        krakend.log_level = log_level
        krakend.config_file = config_file
        krakend.secrets_file = secrets_file
        krakend.policy_file = policy_file

        if 'start' == action:
            krakend.start()
        elif 'stop' == action:
            krakend.stop()
        elif 'restart' == action:
            krakend.restart()
        else:
            usage()
            sys.exit(2)

    sys.exit(0)
